**bold text**# Torch functions

### Overview

An short introduction about PyTorch and about the chosen functions. 
- Torch.nn.functional.conv2d 
- Torch.functional.relu and sigmoid
- Tensor views
- Tensror sparse
- distribution Bernoulli

In [1]:
# Import torch and other required modules
import torch
import torch.nn as nn
import torch.nn.functional as F

## Function 1 - torch.nn.ConvNd

Add some explanations

In [2]:
# Example 1 
weights = torch.randn(8,4,3,3)
inputs = torch.randn( 1,4,5,5)

conv2 = nn.functional.conv2d(inputs, weights, padding=1)
print(conv2)


tensor([[[[ 3.8680e+00,  5.0820e+00, -1.0063e+01, -8.8937e-01,  2.9871e+00],
          [ 4.9803e+00,  1.2524e+00, -3.5393e-01, -5.7376e-02,  6.9019e+00],
          [-5.3350e+00, -9.8769e+00, -3.6961e+00, -3.9565e+00, -4.4567e+00],
          [-6.1955e+00,  2.1419e+00,  2.0403e-01, -2.7475e+00,  1.1002e+01],
          [ 9.4631e+00,  8.7178e-01,  2.1688e+00,  7.1002e+00,  1.4491e+00]],

         [[ 2.5075e+00, -1.3761e+00,  5.8364e+00, -6.6801e+00, -1.5880e+00],
          [-2.2470e+00,  1.1989e+01, -3.5544e+00, -6.0607e+00,  4.7767e+00],
          [ 8.3233e+00, -4.9677e+00, -4.8019e+00,  5.1346e+00,  1.2297e+00],
          [-5.5617e+00, -5.0186e+00,  6.7778e-01, -1.2989e+01, -1.4212e+00],
          [-3.0105e+00, -3.6638e+00,  5.0936e+00, -3.5987e+00, -1.7590e+00]],

         [[ 1.3004e+00,  3.8636e+00,  1.3745e+00, -4.9612e+00, -1.8940e+00],
          [ 2.1954e-02,  1.5935e+00,  8.0963e+00,  5.9663e+00,  1.7166e+00],
          [ 4.0973e+00,  2.3024e+00,  1.8693e+00, -1.5356e-01,  4.0245e+

Explanation about example:create convolutional NN matrix of [1, 8, 5, 5] dim for a kernel given input and filter list values

In [3]:
# Example 2 - working
weights = torch.randn(1,3,2,2)
inputs = torch.randn(5,3,2,2)

conv = nn.functional.conv2d(inputs, weights, padding=1)
print(conv)

tensor([[[[ 0.1695,  1.0453, -4.0867],
          [-0.8918,  4.1409,  0.5377],
          [ 1.1184, -0.7244, -1.2250]]],


        [[[ 0.2823, -0.8084, -0.7433],
          [ 0.2396, -0.0843,  0.8847],
          [ 0.9181, -2.3397,  1.2026]]],


        [[[ 0.2465, -3.2782, -0.9955],
          [-1.1485,  1.2174, -5.2969],
          [ 0.2108, -3.7376,  2.9179]]],


        [[[ 0.8229, -1.3374,  1.7358],
          [-3.0083,  2.0577, -4.0302],
          [ 1.7551, -3.1077, -4.1525]]],


        [[[ 0.6812,  0.2392, -0.9130],
          [-1.0887,  3.0736, -1.1439],
          [ 0.0581, -0.7539, -0.2402]]]])


Explanation about example:create convolutional NN matrix of [5, 1, 3, 3] dim for a kernel given input and filter matrix values

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
filters = torch.randn(1,3,2,2)
inputs = torch.randn(5,3,2,2)

conv = nn.functional.conv2d(inputs, padding=1)


TypeError: conv2d() missing 1 required positional arguments: "weight"

Explanation about example: minimum 3 parameters in order to set the kernel weights of the NN convolutional matrix

Closing comments about when to use this function: to set convolutional matrix in order to manage deep NN learning with invariance characteristics. 

## Function 2 - torch.nn.functional

Applies the rectified linear unit function element-wise.

In [5]:
# Example 1 - working
input=torch.tensor([[1, 2], [3, 4.]])
F.relu(input)

tensor([[1., 2.],
        [3., 4.]])

Explanation about example:Applies the rectified linear unit function element-wise.

In [6]:
# Example 2 - working
F.logsigmoid(torch.tensor([[1, 2, 3, 4], [3, 4., 4, 4]]))

tensor([[-0.3133, -0.1269, -0.0486, -0.0181],
        [-0.0486, -0.0181, -0.0181, -0.0181]])

Explanation about example: Applies the sigmoid function element-wise.

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
input=torch.tensor([[1, 1], [3, 4., 5, 6]])
F.relu(input)

ValueError: expected sequence of length 2 at dim 1 (got 4)

Explanation about example: the dimension must be nxn, means square dim

Closing comments about when to use this function; usually the function set for forward propagate must be done according the NN problem 

---



## Function 3 - Tensor views

view function is meant to reshape the tensor

In [8]:
# Example 1 - working
a = torch.range(1, 16)
print(a)
a.view(4, 4)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])


tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

Explanation about example: the view reshape size must be the same size (16 or 4**2)  previous generated when the torch array is created.

In [25]:
# Example 2 - working
a = torch.range(1, 81)
print(a)
a.view(9, 9)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
        57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70.,
        71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81.])


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24., 25., 26., 27.],
        [28., 29., 30., 31., 32., 33., 34., 35., 36.],
        [37., 38., 39., 40., 41., 42., 43., 44., 45.],
        [46., 47., 48., 49., 50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59., 60., 61., 62., 63.],
        [64., 65., 66., 67., 68., 69., 70., 71., 72.],
        [73., 74., 75., 76., 77., 78., 79., 80., 81.]])

Explanation about example: the view reshape size must be the same size (81 or 9**2) previous generated when the torch array is created.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.range(1, 16)
print(a)
a.view(5, 5)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])


RuntimeError: shape '[5, 5]' is invalid for input of size 16

Explanation about example: breake when the dimension don't achive the same size as tensor array 

Closing comments about when to use this function: to  reshape the dimension of an tesor array previous generated   

## Function 4 - torch.sparse

Torch supports sparse tensors in COO(rdinate) format, which can efficiently store and process tensors for which the majority of elements are zeros.

In [11]:
# Example 1 - working
i = torch.LongTensor([[0, 1, 1],
                          [2, 0, 2]])
v = torch.FloatTensor([3, 4, 5])
torch.sparse.FloatTensor(i, v, torch.Size([2,3])).to_dense()

tensor([[0., 0., 3.],
        [4., 0., 5.]])

Explanation about example: the dense tensor indices give the coordinates to set the list values in a new sparse tensor [0,2][1,0][1,2], and the dense tenstor values give the values in order to set

In [12]:
# Example 2 - working
i = torch.LongTensor([[1, 1, 1],
                          [1, 0, 2]])
v = torch.FloatTensor([1, 1, 1])
torch.sparse.FloatTensor(i, v, torch.Size([2,3])).to_dense()

tensor([[0., 0., 0.],
        [1., 1., 1.]])

Explanation about example: the dense tensor indices give the coordinates to set the list values in a new sparse tensor [1,1][1,0][1,2], and the dense tenstor values give the values in order to set

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
i = torch.LongTensor([[1, 1, 1],
                          [1, 0, 2]])
v = torch.FloatTensor([1, 1])
torch.sparse.FloatTensor(i, v, torch.Size([2,3])).to_dense()

RuntimeError: indices and values must have same nnz, but got nnz from indices: 3, nnz from values: 2

Explanation about example: if there are 3 coordinates is necessary  provide a dense tensor list with 3 values

Closing comments about when to use this function

## Function 5 - distribution.Bernoulli

Add some explanations

In [14]:
# Example 1 - working
m = torch.distributions.bernoulli.Bernoulli(torch.tensor([0.3]))
m.sample()  # 30% chance 1; 70% chance 0


tensor([0.])

Explanation about example: likelihood to sample is 70% chance 0 and 30% chance 1

In [15]:
# Example 2 - working
m = torch.distributions.bernoulli.Bernoulli(torch.tensor([0.5]))
m.sample()  # 50% chance 1; 50% chance 0

tensor([1.])

Explanation about example: likelihood to sample is 50%  chance 0 and 50% chance 1

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
m = torch.distributions.bernoulli.Bernoulli(torch.tensor([1]))
m.sample()  

RuntimeError: "bernoulli_tensor_cpu_p_" not implemented for 'torch.LongTensor'

Explanation about example: the likelihood is not managed by Long numbers param

Closing comments about when to use this function: when Bernoulli likelihood is desired to assign

## Conclusion

In this notebook is About torch.Tensor functions in order to be explained and presented some examples, I will continue in the next notebook regarding to Train Your First Model

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [17]:
!pip install jovian --upgrade --quiet

In [1]:
import jovian

<IPython.core.display.Javascript object>

[jovian] Update Available: 0.2.14 --> 0.2.16
[jovian] Run `!pip install jovian --upgrade` to upgrade


In [2]:
jovian.commit(filename='01_tensor_operations.ipynb', artifact='torch-1.0.1-cp37-cp37m-win_amd64.whl')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "adess23/01-tensor-operations-0830b" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/adess23/01-tensor-operations-0830b


'https://jovian.ml/adess23/01-tensor-operations-0830b'